baseURL = 'https://ashwinyue.github.io/xyz-kit/'
languageCode = 'zh-cn'
title = 'xyz-kit'
theme = 'hextra'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[params]
  description = "轻量级文本处理工具"
  
  [params.navbar]
    displayTitle = true
    displayLogo = false
    
    [[params.navbar.menu]]
      name = "文档"
      pageRef = "/docs"
      weight = 1
    
    [[params.navbar.menu]]
      name = "GitHub"
      url = "https://github.com/ashwinyue/xyz-kit"
      weight = 2
      
    [[params.navbar.menu]]
      name = "下载"
      url = "https://github.com/ashwinyue/xyz-kit/releases/latest"
      weight = 3

  [params.footer]
    displayCopyright = true
    displayPoweredBy = false

  [params.theme]
    default = "system"
    displayToggle = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
