baseURL = 'https://ashwinyue.github.io/xyz-kit/'
languageCode = 'zh-cn'
title = 'xyz-kit 文档'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/ashwinyue/xyz-kit'
  BookEditPath = 'edit/main/docs-site/content'
  BookSearch = true
  BookComments = false
  BookPortableLinks = true
  BookServiceWorker = true

[menu]
  [[menu.before]]
    name = 'GitHub'
    url = 'https://github.com/ashwinyue/xyz-kit'
    weight = 1
  [[menu.before]]
    name = '下载'
    url = 'https://github.com/ashwinyue/xyz-kit/releases/latest'
    weight = 2
